---
# KNeighborsRegressor - Copia

---

In [53]:
def Erro(y_previsto,y_base_teste):
    lista_erro = []
    for i,e in zip(y_previsto,y_base_teste):
        if i < e:
            dif = e-i
            lista_erro.append(dif)
        else: 
            dif = i-e
            lista_erro.append(dif)
    return lista_erro

def Classificador(Erro):
    lista_classificacao = []
    for erros in Erro:
        if erros<=0.5:
            classfica = "Certo"
            lista_classificacao.append(classfica)
        else:
            classifica = "Errado"
            lista_classificacao.append(classfica)
    return lista_classificacao 

def Acuracia(Classificador,Erro):
    data = {
    'Y_predict': y_predict,
    'Y_test': y_test,
    'Erro': Erro, 
    'Classificação': Classificador,
    }
    tabela = pd.DataFrame(data, columns=['Y_predict', 'Y_test','Erro','Classificação'])
    tabela.head(5)
    contador=0
    for c in Classificador: 
        if c == "Certo": 
            contador+=1
    acertou=(contador/len(Classificador))*100
    return acertou 
    

In [23]:
# --------------------- IMPORTANDO BIBLIOTECA ----------------------
%matplotlib inline
# !pip install mglearn
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.model_selection import train_test_split
import mglearn 
from sklearn.neighbors import KNeighborsRegressor
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [24]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [25]:
# ---------------- lendo arquivos ----------------
dados = pd.read_excel("HappinessAlcoholConsumption.xls")

In [26]:
X =  dados[['HDI', 'GDP_PerCapita', 'Beer_PerCapita', 'Spirit_PerCapita', 'Wine_PerCapita']]
y = dados["HappinessScore"]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=RANDOM_SEED)

---
# Primeira Interação 

---

In [28]:
reg = KNeighborsRegressor(n_neighbors=5)
reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [29]:
y_predict = reg.predict(X_test)
y_predict

array([7.2824, 6.2248, 5.1072, 3.643 , 7.0554, 5.8292, 5.7534, 3.8306,
       5.4962, 6.875 , 5.7138, 3.9354, 6.348 ])

In [55]:
a = Erro(y_predict,y_test)
b = Classificador(a)
c = Acuracia(b,a)
c

100.0

In [18]:
erro=[]
for i,e in zip(y_predict,y_test):
    if i<e:
     diferenca= e-i
     erro.append(diferenca)
    else:
     diferenca= i-e
     erro.append(diferenca)

classificacao=[]
for erros in erro: 
    if erros< 0.5: 
        classfi= 'Certo'
        classificacao.append(classfi)
    else:
        classfi= 'Errado'
        classificacao.append(classfi)

In [19]:
data = {
'Y_predict': y_predict,
'Y_test': y_test,
'Erro': erro, 
'Classificação': classificacao,
}
tabela = pd.DataFrame(data, columns=['Y_predict', 'Y_test','Erro','Classificação'])
tabela.head(5)

Y_predict  Y_test    Erro Classificação
18     7.2824   6.871  0.4114         Certo
45     6.2248   5.956  0.2688         Certo
47     5.1072   5.919  0.8118        Errado
89     3.6430   4.635  0.9920        Errado
4      7.0554   7.413  0.3576         Certo

In [20]:
contador=0
for c in classificacao: 
    if c == "Certo": 
        contador+=1
acertou=(contador/len(classificacao))*100
print("A regressão Kneighbors acertou {0}%".format(acertou))

A regressão Kneighbors acertou 61.53846153846154%


---
# Segunda Interação 

---

In [21]:
X2 =  dados[['HDI', 'GDP_PerCapita']]
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y, test_size=0.1, random_state=RANDOM_SEED)

In [22]:
reg.fit(X_train2, y_train2)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [23]:
y_predict2 = reg.predict(X_test2)
y_predict2

array([7.152 , 5.4852, 6.0942, 3.643 , 7.1462, 5.1418, 5.5162, 3.8394,
       5.561 , 6.2494, 5.7628, 3.9354, 6.5374])

In [24]:
erro=[]
for i,e in zip(y_predict2,y_test2):
    if i<e:
     diferenca = e-i
     erro.append(diferenca)
    else:
     diferenca = i-e
     erro.append(diferenca)

classificacao=[]
for erros in erro: 
    if erros< 0.5: 
        classfi= 'Certo'
        classificacao.append(classfi)
    else:
        classfi= 'Errado'
        classificacao.append(classfi)

In [25]:
data = {
'Y_predict': y_predict,
'Y_test': y_test,
'Erro': erro, 
'Classificação': classificacao,
}
tabela = pd.DataFrame(data, columns=['Y_predict', 'Y_test','Erro','Classificação'])
tabela.head(5)

Y_predict  Y_test    Erro Classificação
18     7.2824   6.871  0.2810         Certo
45     6.2248   5.956  0.4708         Certo
47     5.1072   5.919  0.1752         Certo
89     3.6430   4.635  0.9920        Errado
4      7.0554   7.413  0.2668         Certo

In [26]:
contador=0
for c in classificacao: 
    if c == "Certo": 
        contador+=1
acertou=(contador/len(classificacao))*100
print("A regressão Kneighbors acertou {0}%".format(acertou))

A regressão Kneighbors acertou 69.23076923076923%


---
# Passando log no GPD PerCapita

---

In [27]:
GPD= dados["GDP_PerCapita"]

In [30]:
dados.loc[:,"LOG_GPD"] = np.log(GPD)

In [31]:
dados

Country                           Region Hemisphere  \
0                 Denmark                   Western Europe      north   
1             Switzerland                   Western Europe      north   
2                 Iceland                   Western Europe      north   
3                  Norway                   Western Europe      north   
4                 Finland                   Western Europe      north   
5                  Canada                    North America      north   
6             Netherlands                   Western Europe      north   
7             New Zealand        Australia and New Zealand      south   
8               Australia        Australia and New Zealand      south   
9                  Sweden                   Western Europe      north   
10                 Israel  Middle East and Northern Africa      north   
11                Austria                   Western Europe      north   
12          United States                    North America      north   
13             Costa Rica      Latin America and Caribbean      north   
14                Germany                   Western Europe      north   
15                 Brazil      Latin America and Caribbean       both   
16                Belgium                   Western Europe      north   
17                Ireland                   Western Europe      north   
18             Luxembourg                   Western Europe      north   
19                 Mexico      Latin America and Caribbean      north   
20              Singapore                Southeastern Asia      north   
21         United Kingdom                   Western Europe      north   
22                  Chile      Latin America and Caribbean      south   
23                 Panama      Latin America and Caribbean      north   
24              Argentina      Latin America and Caribbean      south   
25         Czech Republic       Central and Eastern Europe      north   
26   United Arab Emirates  Middle East and Northern Africa      north   
27                Uruguay      Latin America and Caribbean      south   
28                  Malta                   Western Europe      north   
29               Colombia      Latin America and Caribbean       both   
..                    ...                              ...        ...   
92           South Africa               Sub-Saharan Africa      south   
93                  Egypt  Middle East and Northern Africa      north   
94                Armenia       Central and Eastern Europe      north   
95                  Kenya               Sub-Saharan Africa       both   
96                Ukraine       Central and Eastern Europe      north   
97                  Ghana               Sub-Saharan Africa      north   
98        Dem. Rep. Congo               Sub-Saharan Africa      south   
99                Georgia       Central and Eastern Europe      north   
100            Rep. Congo               Sub-Saharan Africa      south   
101               Senegal               Sub-Saharan Africa      north   
102              Bulgaria       Central and Eastern Europe      north   
103              Zimbabwe               Sub-Saharan Africa      south   
104                Malawi               Sub-Saharan Africa      south   
105                 Gabon               Sub-Saharan Africa      south   
106                  Mali               Sub-Saharan Africa      north   
107                 Haiti      Latin America and Caribbean      north   
108              Botswana               Sub-Saharan Africa      south   
109               Comoros               Sub-Saharan Africa      south   
110         Cote d'Ivoire               Sub-Saharan Africa      north   
111              Cambodia                Southeastern Asia      north   
112                Angola               Sub-Saharan Africa      south   
113                 Niger               Sub-Saharan Africa      north   
114                  Chad               Sub-Saharan Africa      north   
115

In [32]:
X3 =  dados[['HDI', 'LOG_GPD']]
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y, test_size=0.1, random_state=RANDOM_SEED)

In [33]:
reg.fit(X_train3, y_train3)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [34]:
y_predict3 = reg.predict(X_test3)
y_predict3

array([6.4564, 5.4852, 6.0942, 3.8938, 7.0992, 5.1418, 5.5162, 3.8178,
       5.561 , 6.4778, 6.2158, 4.0096, 6.5374])

In [35]:
erro=[]
for i,e in zip(y_predict3,y_test3):
    if i<e:
     diferenca = e-i
     erro.append(diferenca)
    else:
     diferenca = i-e
     erro.append(diferenca)

classificacao=[]
for erros in erro: 
    if erros< 0.5: 
        classfi= 'Certo'
        classificacao.append(classfi)
    else:
        classfi= 'Errado'
        classificacao.append(classfi)

In [36]:
data = {
'Y_predict': y_predict,
'Y_test': y_test,
'Erro': erro, 
'Classificação': classificacao,
}
tabela = pd.DataFrame(data, columns=['Y_predict', 'Y_test','Erro','Classificação'])
tabela.head(5)

Y_predict  Y_test    Erro Classificação
18     7.2824   6.871  0.4146         Certo
45     6.2248   5.956  0.4708         Certo
47     5.1072   5.919  0.1752         Certo
89     3.6430   4.635  0.7412        Errado
4      7.0554   7.413  0.3138         Certo

In [37]:
contador=0
for c in classificacao: 
    if c == "Certo": 
        contador+=1
acertou=(contador/len(classificacao))*100
print("A regressão Kneighbors acertou {0}%".format(acertou))

A regressão Kneighbors acertou 53.84615384615385%


# Analisando com outras variaveis

In [39]:
X4 =  dados[['HDI', 'LOG_GPD', 'Beer_PerCapita', 'Spirit_PerCapita', 'Wine_PerCapita']]
y4 = dados["HappinessScore"]

In [40]:
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.1, random_state=RANDOM_SEED)

In [42]:
reg.fit(X4_train, y4_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [44]:
y_predict4 = reg.predict(X4_test)
y_predict4

array([6.9122, 6.2248, 5.1072, 4.0006, 7.0554, 5.8292, 6.1482, 5.1322,
       5.4962, 6.875 , 5.7138, 3.891 , 6.348 ])

In [46]:
erro=[]
for i,e in zip(y_predict4,y4_test):
    if i<e:
     diferenca = e-i
     erro.append(diferenca)
    else:
     diferenca = i-e
     erro.append(diferenca)

classificacao=[]
for erros in erro: 
    if erros< 0.5: 
        classfi= 'Certo'
        classificacao.append(classfi)
    else:
        classfi= 'Errado'
        classificacao.append(classfi)

In [47]:
data = {
'Y_predict': y_predict,
'Y_test': y_test,
'Erro': erro, 
'Classificação': classificacao,
}
tabela = pd.DataFrame(data, columns=['Y_predict', 'Y_test','Erro','Classificação'])
tabela.head(5)

Y_predict  Y_test    Erro Classificação
18     7.2824   6.871  0.0412         Certo
45     6.2248   5.956  0.2688         Certo
47     5.1072   5.919  0.8118        Errado
89     3.6430   4.635  0.6344        Errado
4      7.0554   7.413  0.3576         Certo

In [48]:
contador=0
for c in classificacao: 
    if c == "Certo": 
        contador+=1
acertou=(contador/len(classificacao))*100
print("A regressão Kneighbors acertou {0}%".format(acertou))

A regressão Kneighbors acertou 46.15384615384615%


# Analisando mais variaveis 


In [8]:
#lendo arquivos
mortalidade_infantil = pd.read_excel('child_mortality_0_5_year_olds_dying_per_1000_born.xlsx')
inflacao = pd.read_excel('inflation_annual_percent.xlsx')
crianca_p_mulher = pd.read_excel('children_per_woman_total_fertility.xlsx')
expectativa_vida = pd.read_excel('life_expectancy_years.xlsx')
desemprego = pd.read_excel('DadoDeDesemprego.xls', sheet_name="Data", skiprows=3)
#Colocar index e pegar o ano de 2016 - Mortalidade Infantil 
mort_infantil=mortalidade_infantil.set_index("country")
mort_infantil_2016 = mort_infantil.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 - Inflação
infla=inflacao.set_index("country")
infla_2016 = infla.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 -Criança por Mulher
crianca_mulher=crianca_p_mulher.set_index("country")
crianca_mulher_2016 = crianca_mulher.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 - Expectativa de vida 
expec_vida=expectativa_vida.set_index("country")
expec_vida_2016 = expec_vida.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 - Desemprego 
desemp_2016 = desemprego.loc[:, ["Country Name" ,"2016"]]
desemp_2016=desemp_2016.set_index("Country Name")
#juntando tabelas
df = mort_infantil_2016.join(infla_2016, how='inner', lsuffix='_mortalidade', rsuffix='_inflação')
df1 = df.join(crianca_mulher_2016, how="inner")
df1.columns = ['Mortalidade', 'Inflação', 'Criança p/ Mulher']
df2 = df1.join(expec_vida_2016, how="inner")
df2.columns = ['Mortalidade', 'Inflação', 'Criança p/ Mulher', 'Expec de Vida']
df3= df2.join(desemp_2016, how="inner")
df3.columns = ['Mortalidade', 'Inflação', 'Criança p/ Mulher', 'Expec de Vida', 'Desemprego']

#tirando valores nulos
df3=df3.dropna()
#lendo dados Felicidade e álcool 
dados = pd.read_excel("HappinessAlcoholConsumption.xls")

#Arrumando Index
dados_indice = dados.set_index("Country")
tudo= dados_indice.join(df3, how="inner")

In [15]:
tudo.head()

Region Hemisphere  HappinessScore  HDI  GDP_PerCapita  \
Denmark      Western Europe      north           7.526  928         53.579   
Switzerland  Western Europe      north           7.509  943         79.866   
Iceland      Western Europe      north           7.501  933         60.530   
Norway       Western Europe      north           7.498  951         70.890   
Finland      Western Europe      north           7.413  918         43.433   

             Beer_PerCapita  Spirit_PerCapita  Wine_PerCapita  Mortalidade  \
Denmark                 224                81             278          4.4   
Switzerland             185               100             280          4.1   
Iceland                 233                61              78          2.1   
Norway                  169                71             129          2.6   
Finland                 263               133              97          2.3   

             Inflação  Criança p/ Mulher  Expec de Vida  Desemprego  
Denmark       -0.0464               1.74           80.8      6.1807  
Switzerland   -0.5660               1.55           83.1      4.9179  
Iceland        2.1100               1.93           82.3      2.9779  
Norway        -1.1100               1.82           82.1      4.6789  
Finland        0.7910               1.77           81.7      8.8184

In [18]:
X5 = ["Mortalidade","HDI","GDP_PerCapita","Inflação","Criança p/ Mulher","Expec de Vida","Desemprego"]

In [19]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y, test_size=0.1, random_state=RANDOM_SEED)

ValueError: Found input variables with inconsistent numbers of samples: [7, 122]