---
# KNeighborsRegressor - Copia

---

In [1]:
# --------------------- IMPORTANDO BIBLIOTECA ----------------------
%matplotlib inline
# !pip install mglearn
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.model_selection import train_test_split
# import mglearn 
from sklearn.neighbors import KNeighborsRegressor
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [2]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [3]:
# ---------------- lendo arquivos ----------------
dados = pd.read_excel("HappinessAlcoholConsumption.xls")

In [4]:
# ------------- separando as colunas ------------
X =  dados[['HDI', 'GDP_PerCapita', 'Beer_PerCapita', 'Spirit_PerCapita', 'Wine_PerCapita']]
y = dados["HappinessScore"]

In [5]:
# criando base de teste e treinamento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=RANDOM_SEED)

In [48]:
# --------------- DEF para acuracia --------------- 
def Erro(y_previsto,y_base_teste):
    lista_erro = []
    for i,e in zip(y_previsto,y_base_teste):
        if i < e:
            dif = e-i
            lista_erro.append(dif)
        else: 
            dif = i-e
            lista_erro.append(dif)
    return lista_erro

def Classificador(lista_erro):
    lista_classificacao = []
    for erros in lista_erro:
        if erros<0.5:
            classifica = 'Certo'
            lista_classificacao.append(classifica)
        else:
            classifica = 'Errado'
            lista_classificacao.append(classifica)
    return lista_classificacao 

def Acuracia(Classificador,Erro,y_predict,y_test):
#     print("y predict: ", y_predict)
#     print("y test: ", y_test )
    data = {
    'Y_predict': y_predict,
    'Y_test': y_test,
    'Erro': Erro, 
    'Classificação': Classificador,
    }
    tabela = pd.DataFrame(data, columns=['Y_predict', 'Y_test','Erro','Classificação'])
    tabela.head(5)
    contador=0
    for c in Classificador: 
        if c == "Certo": 
            contador+=1
    acertou=(contador/len(Classificador))*100
    return acertou 
    

---
# Primeira Interação 

---

In [7]:
reg = KNeighborsRegressor(n_neighbors=5)
reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [8]:
y_predict = reg.predict(X_test)
y_predict

array([7.2824, 6.2248, 5.1072, 3.643 , 7.0554, 5.8292, 5.7534, 3.8306,
       5.4962, 6.875 , 5.7138, 3.9354, 6.348 ])

In [9]:
erro = Erro(y_predict,y_test)
classificando = Classificador(erro)
acuraria = Acuracia(classificando,erro)
print("A regressão Kneighbors acertou {0}%".format(acuraria))

A regressão Kneighbors acertou 61.53846153846154%


---
# Segunda Interação 

---

In [10]:
X2 =  dados[['HDI', 'GDP_PerCapita']]
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y, test_size=0.1, random_state=RANDOM_SEED)

In [11]:
reg.fit(X_train2, y_train2)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [12]:
y_predict2 = reg.predict(X_test2)
y_predict2

array([7.152 , 5.4852, 6.0942, 3.643 , 7.1462, 5.1418, 5.5162, 3.8394,
       5.561 , 6.2494, 5.7628, 3.9354, 6.5374])

In [13]:
erro2 = Erro(y_predict2,y_test2)
classificando2 = Classificador(erro2)
acuraria2 = Acuracia(classificando2,erro2)
print("A regressão Kneighbors acertou {0}%".format(acuraria2))

A regressão Kneighbors acertou 69.23076923076923%


---
# Passando log no GPD PerCapita

---

In [14]:
GPD= dados["GDP_PerCapita"]

In [15]:
dados.loc[:,"LOG_GPD"] = np.log(GPD)

In [16]:
dados.head()

Country          Region Hemisphere  HappinessScore  HDI  GDP_PerCapita  \
0      Denmark  Western Europe      north           7.526  928         53.579   
1  Switzerland  Western Europe      north           7.509  943         79.866   
2      Iceland  Western Europe      north           7.501  933         60.530   
3       Norway  Western Europe      north           7.498  951         70.890   
4      Finland  Western Europe      north           7.413  918         43.433   

   Beer_PerCapita  Spirit_PerCapita  Wine_PerCapita   LOG_GPD  
0             224                81             278  3.981157  
1             185               100             280  4.380350  
2             233                61              78  4.103139  
3             169                71             129  4.261129  
4             263               133              97  3.771220

In [17]:
X3 =  dados[['HDI', 'LOG_GPD']]
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y, test_size=0.1, random_state=RANDOM_SEED)

In [18]:
reg.fit(X_train3, y_train3)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [19]:
y_predict3 = reg.predict(X_test3)
y_predict3

array([6.4564, 5.4852, 6.0942, 3.8938, 7.0992, 5.1418, 5.5162, 3.8178,
       5.561 , 6.4778, 6.2158, 4.0096, 6.5374])

In [20]:
erro3 = Erro(y_predict3,y_test3)
classificando3 = Classificador(erro3)
acuraria3 = Acuracia(classificando3,erro3)
print("A regressão Kneighbors acertou {0}%".format(acuraria3))

A regressão Kneighbors acertou 53.84615384615385%


# Analisando com outras variaveis

In [21]:
X4 =  dados[['HDI', 'LOG_GPD', 'Beer_PerCapita', 'Spirit_PerCapita', 'Wine_PerCapita']]
y4 = dados["HappinessScore"]

In [22]:
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.1, random_state=RANDOM_SEED)

In [23]:
reg.fit(X4_train, y4_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [24]:
y_predict4 = reg.predict(X4_test)
y_predict4

array([6.9122, 6.2248, 5.1072, 4.0006, 7.0554, 5.8292, 6.1482, 5.1322,
       5.4962, 6.875 , 5.7138, 3.891 , 6.348 ])

In [25]:
erro4 = Erro(y_predict4,y4_test)
classificando4 = Classificador(erro4)
acuraria4 = Acuracia(classificando4,erro4)
print("A regressão Kneighbors acertou {0}%".format(acuraria4))

A regressão Kneighbors acertou 46.15384615384615%


# Analisando mais variaveis 


In [26]:
#lendo arquivos
mortalidade_infantil = pd.read_excel('child_mortality_0_5_year_olds_dying_per_1000_born.xlsx')
inflacao = pd.read_excel('inflation_annual_percent.xlsx')
crianca_p_mulher = pd.read_excel('children_per_woman_total_fertility.xlsx')
expectativa_vida = pd.read_excel('life_expectancy_years.xlsx')
desemprego = pd.read_excel('DadoDeDesemprego.xls', sheet_name="Data", skiprows=3)
#Colocar index e pegar o ano de 2016 - Mortalidade Infantil 
mort_infantil=mortalidade_infantil.set_index("country")
mort_infantil_2016 = mort_infantil.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 - Inflação
infla=inflacao.set_index("country")
infla_2016 = infla.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 -Criança por Mulher
crianca_mulher=crianca_p_mulher.set_index("country")
crianca_mulher_2016 = crianca_mulher.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 - Expectativa de vida 
expec_vida=expectativa_vida.set_index("country")
expec_vida_2016 = expec_vida.loc[:, [2016]]

#Colocar index e pegar o ano de 2016 - Desemprego 
desemp_2016 = desemprego.loc[:, ["Country Name" ,"2016"]]
desemp_2016=desemp_2016.set_index("Country Name")
#juntando tabelas
df = mort_infantil_2016.join(infla_2016, how='inner', lsuffix='_mortalidade', rsuffix='_inflação')
df1 = df.join(crianca_mulher_2016, how="inner")
df1.columns = ['Mortalidade', 'Inflação', 'Criança p/ Mulher']
df2 = df1.join(expec_vida_2016, how="inner")
df2.columns = ['Mortalidade', 'Inflação', 'Criança p/ Mulher', 'Expec de Vida']
df3= df2.join(desemp_2016, how="inner")
df3.columns = ['Mortalidade', 'Inflação', 'Criança p/ Mulher', 'Expec de Vida', 'Desemprego']

#tirando valores nulos
df3=df3.dropna()
#lendo dados Felicidade e álcool 
dados = pd.read_excel("HappinessAlcoholConsumption.xls")

#Arrumando Index
dados_indice = dados.set_index("Country")
tudo= dados_indice.join(df3, how="inner")

In [27]:
tudo.head(2)

Region Hemisphere  HappinessScore  HDI  GDP_PerCapita  \
Denmark      Western Europe      north           7.526  928         53.579   
Switzerland  Western Europe      north           7.509  943         79.866   

             Beer_PerCapita  Spirit_PerCapita  Wine_PerCapita  Mortalidade  \
Denmark                 224                81             278          4.4   
Switzerland             185               100             280          4.1   

             Inflação  Criança p/ Mulher  Expec de Vida  Desemprego  
Denmark       -0.0464               1.74           80.8      6.1807  
Switzerland   -0.5660               1.55           83.1      4.9179

In [28]:
X5 = tudo[["Mortalidade","HDI","GDP_PerCapita","Inflação","Criança p/ Mulher","Expec de Vida","Desemprego"]]
y5 = tudo["HappinessScore"]

In [29]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.1, random_state=RANDOM_SEED)

In [30]:
reg.fit(X_train5, y_train5)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [31]:
y_predict5 = reg.predict(X_test5)
y_predict5

array([7.1462, 5.8306, 6.7562, 7.1948, 5.6548, 5.5288, 5.4334, 5.8884])

In [32]:
y_test5

Finland       7.413
Ecuador       5.976
Israel        7.267
Denmark       7.526
Latvia        5.560
Romania       5.528
Albania       4.655
Azerbaijan    5.291
Name: HappinessScore, dtype: float64

In [47]:
erro5 = Erro(y_predict5,y_test5.values)
classificando5 = Classificador(erro5)
acuraria5= Acuracia(classificando5,erro5,y_predict5,y_test5)
print("A regressão Kneighbors acertou {0}%".format(acuraria5))


y predict:  [7.1462 5.8306 6.7562 7.1948 5.6548 5.5288 5.4334 5.8884]
y test:  Finland       7.413
Ecuador       5.976
Israel        7.267
Denmark       7.526
Latvia        5.560
Romania       5.528
Albania       4.655
Azerbaijan    5.291
Name: HappinessScore, dtype: float64
A regressão Kneighbors acertou 62.5%


In [34]:
len(y_predict5)

8

In [44]:
y_test5

Finland       7.413
Ecuador       5.976
Israel        7.267
Denmark       7.526
Latvia        5.560
Romania       5.528
Albania       4.655
Azerbaijan    5.291
Name: HappinessScore, dtype: float64

In [45]:
y_predict5

array([7.1462, 5.8306, 6.7562, 7.1948, 5.6548, 5.5288, 5.4334, 5.8884])

In [41]:
len(y_test5.values)

8