---
# SGD Regression


A maioria dos aplicativos de aprendizado de máquina / aprendizado profundo usa uma variante de descida de gradiente chamada descida de gradiente estocástico (SGD), na qual, em vez de atualizar parâmetros com base na derivada do conjunto de dados em cada etapa, você atualiza com base na derivada de uma amostra escolhida aleatoriamente . Além de ser menos tributável computacionalmente, a pesquisa mostrou que a aleatoriedade envolvida no SGD permite convergir e superar os mínimos locais mais rapidamente.

---

In [56]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
from sklearn.model_selection import train_test_split



In [57]:
os.getcwd()

'/Users/stephanieliu/Desktop/GitHub/SegundoSemestre/CD_Projeto3'

In [58]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [59]:
dados = pd.read_excel("HappinessAlcoholConsumption.xls")

In [70]:
X =  dados[['HDI', 'GDP_PerCapita', 'Beer_PerCapita', 'Spirit_PerCapita', 'Wine_PerCapita']]
y = dados["HappinessScore"]

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=RANDOM_SEED)

In [72]:
GPD = dados["GDP_PerCapita"]
beer = dados["Beer_PerCapita"]
Happy = dados["HappinessScore"]


In [73]:
# list(dados)

In [74]:
# x = dados["GDP_PerCapita"]
# x = np.log(x)

In [75]:
# sns.jointplot(x, Happy);
# plt.show()

In [76]:
M=1


## Testando códigos do livro!!

In [77]:
from sklearn.linear_model import SGDRegressor

In [78]:
sgd_reg = SGDRegressor(n_iter=50, penalty=None, eta0=0.1)

In [79]:
# list(dados)

In [80]:
# x = dados[['HDI', 'GDP_PerCapita', 'Beer_PerCapita', 'Spirit_PerCapita', 'Wine_PerCapita']]

In [81]:
sgd_reg.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
       eta0=0.1, fit_intercept=True, l1_ratio=0.15,
       learning_rate='invscaling', loss='squared_loss', max_iter=None,
       n_iter=50, n_iter_no_change=5, penalty=None, power_t=0.25,
       random_state=None, shuffle=True, tol=None, validation_fraction=0.1,
       verbose=0, warm_start=False)

In [82]:
sgd_reg.intercept_, sgd_reg.coef_

(array([-2.27080075e+10]),
 array([ 7.73768549e+12,  2.75578168e+12,  1.70730205e+12, -8.12416846e+12,
         5.83910838e+12]))

In [83]:
sgd_reg.predict([[0,0,0,0,0]])

array([-2.27080075e+10])

# Plotando o gráfico 